// tokeniser.h : shared definition for tokeniser.l and compilateur.cpp

enum TOKEN {FEOF, UNKNOWN, NUMBER, ID, STRINGCONST, RBRACKET, LBRACKET, RPARENT, LPARENT, COMMA, 
SEMICOLON, DOT, ADDOP, MULOP, RELOP, NOT, ASSIGN, BEG, END, FOR, TO, DO, ELSE, IF, WHILE, THEN, DISPLAY, COLON, VAR, CHARCONST, CASE, OF, VIDE, REPEAT, UNTIL};

enum TYPES {INTEGER, BOOLEAN, DOUBLE, CHAR};